# Site settings
name: blog
email: 2510764133@qq.com
author: huangwei
url: http://huang314.cn/
resume_site: http://huang314.cn/
github: https://mayunmeiyouming.github.io/blog/
baseurl: "/blog"
description: Actually, This is blog!
meta_description: 个人博客;学而不思则罔;思而不学则殆;生命不止;折腾不休
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: mayunmeiyouming

# Build settings
markdown: kramdown

baidu_analysis: 732119f324b13d7ba962f0d22dd41759

