# Site settings
name: blog
email: 2510764133@qq.com
author: huangwei
url: https://mayunmeiyouming.github.io/blog
resume_site: https://mayunmeiyouming.github.io/blog/
github: https://mayunmeiyouming.github.io/blog/
baseurl: "/blog"
description: Actually, This is blog!
meta_description: 个人博客;学而不思则罔;思而不学则殆;生命不止;折腾不休
motto: It's our wits that make us men.
banner: 我是黄伟

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: luoyan35714

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

